# Generated by Django 3.2 on 2021-04-28 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banners/')),
                ('quote', models.CharField(max_length=30)),
                ('tag1', models.CharField(max_length=10)),
                ('tag2', models.CharField(max_length=10)),
                ('tag3', models.CharField(max_length=10)),
            ],
        ),
    ]
